### ISSUE TITLE
Wrong translation of "scalability" word in French

### ISSUE THREAD

**Issue by cmaneu** [MicrosoftDocs/architecture-center.fr-fr#4]
The word "scalability" was translated by "extensibilité", which means "extensibility". A better translation would be "mise à l'échelle". I don't think we have a word that exactly matches the "scalability" English word.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: b79636ce-83ec-b5ba-fc6b-25c397516dd9
* Version Independent ID: 4f8cc5c2-4473-1ca8-b901-6329eb920e8c
* Content: [Liste de contrôle de l’extensibilité - Azure Design Review Framework](https://docs.microsoft.com/fr-fr/azure/architecture/checklist/scalability#feedback)
* Content Source: [docs/checklist/scalability.md](https://github.com/microsoftdocs/architecture-center.fr-fr/blob/live/docs/checklist/scalability.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by srvbpigh** [comment]
Hello, @cmaneu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @cmaneu
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/architecture/checklist/scalability

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
